version: '3.9'

services:
  movies:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
        VITE_API_KEY: ${VITE_API_KEY}
        VITE_IMAGE_BASE_URL: ${VITE_IMAGE_BASE_URL}
    ports:
      - '3000:80'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
